### ISSUE TITLE
Working Sunsynk Config

### ISSUE THREAD

**Issue by bensebborn** [springfall2008/predbat_addon#18]
Here's my working Sunsynk config

apps.yaml

```
---
pred_bat:
  module: predbat
  class: PredBat

  # Sets the prefix for all created entities in HA - only change if you want to run more than once instance
  prefix: predbat

  
  soc_max:
   - 28.8
   
  battery_rate_max:
   - 9500
   
  battery_min_soc: 
   - 10
   
  # Timezone to work in
  timezone: Europe/London

  # Currency, symbol for main currency second symbol for 1/100s e.g. $ c or £ p or e c
  currency_symbols:
   - '£'
   - 'p'

  # Number of threads to use in plan calculation
  # Can be auto for automatic, 0 for off or values 1-N for a fixed number
  threads: 4



  # To disable set it to 1440
  load_filter_threshold: 30

  load_today:
    - sensor.total_house_load_today_filtered
  import_today:
    - sensor.grid_import_daily
  export_today:
    - sensor.grid_export_daily
  pv_today:
    - sensor.total_solar_output_today_filtered
    
  solcast_host: 'https://api.solcast.com.au'
  solcast_api_key:
   - 'xx'
   - 'xx'
  solcast_poll_hours: 4
    
  
  num_inverters: 1
  inverter_type: SK

  charge_start_service:
    service: automation.trigger
    entity_id: "automation.sunsynk_force_charge"

  charge_stop_service:
    service: automation.trigger
    entity_id: "automation.sunsynk_stop_force_charge"

  discharge_start_service:
    service: automation.trigger
    entity_id: "automation.sunsynk_force_discharge"


  battery_power:
     - number.sunsynk_inverter_battery_power

  pv_power:
    - sensor.total_solar_output
    
  load_power:
    - sensor.calculated_house_load_w

  soc_kw:
     - sensor.sunsynk_battery_soc_kw


  charge_limit:
     - number.sunsynk_inverter_capacity_point_6
 
  timed_charge_current:
   - number.sunsynk_inverter_max_grid_charge_current
  timed_discharge_current:
   - number.sunsynk_inverter_max_discharge_current
  battery_voltage:
   - sensor.sunsynk_inverter_battery_voltage

  # Inverter max AC limit (one per inverter). E.g for a 3.6kw inverter set to 3600
  # If you have a second inverter for PV only please add the two values together
  inverter_limit:
    - 18000



 

  battery_charge_power_curve: 'auto'

  inverter_clock_skew_start: 0
  inverter_clock_skew_end: 0
  inverter_clock_skew_discharge_start: 0
  inverter_clock_skew_discharge_end: 0

  clock_skew: 0

  pv_forecast_today: re:(sensor.(solcast_|)(pv_forecast_|)forecast_today)

  pv_forecast_tomorrow: re:(sensor.(solcast_|)(pv_forecast_|)forecast_tomorrow)
  pv_forecast_d3: re:(sensor.(solcast_|)(pv_forecast_|)forecast_(day_3|d3))
  pv_forecast_d4: re:(sensor.(solcast_|)(pv_forecast_|)forecast_(day_4|d4))


  car_charging_energy: 'sensor.myenergi_zappi_19556152_charge_added_session_2'


  num_cars: 1

  car_charging_planned:
    - 'sensor.myenergi_zappi_19556152_plug_status_2'

  car_charging_planned_response:
    - 'yes'
    - 'on'
    - 'true'
    - 'connected'
    - 'ev connected'
    - 'charging'
    - 'paused'
    - 'waiting for car demand'
    - 'waiting for ev'
    - 'scheduled'
    - 'enabled'
    - 'latched'
    - 'locked'
    - 'plugged in'


  
  car_charging_now_response:
    - 'yes'
    - 'on'
    - 'true'

    
  
  octopus_intelligent_slot: 're:(binary_sensor.octopus_energy_intelligent_dispatching)'
  octopus_ready_time: 're:(time.octopus_energy([0-9a-z_]+|)_intelligent_ready_time)'
  octopus_charge_limit: 're:(number.octopus_energy([0-9a-z_]+|)_intelligent_charge_limit)'
  
  octopus_saving_session: 're:(binary_sensor.octopus_energy([0-9a-z_]+|)_saving_session(s|))'
  octopus_saving_session_octopoints_per_penny: 8


 metric_octopus_import: 'sensor.octopus_energy_electricity_23e1048870_1610013470677_current_rate'
 metric_octopus_export: 'sensor.octopus_energy_electricity_23e1048870_1650000177535_export_current_rate'

  metric_standing_charge: 'sensor.octopus_energy_electricity_current_standing_charge'


  days_previous:
    - 1
    - 7

  
  days_previous_weight:
    - 1

 forecast_hours: 48
 
  battery_scaling:
    - 1.0

 
  import_export_scaling: 1.0

```

Then I have three automations which control charge/discharge as referenced in the config:

**Sunsynk: Force Charge**
Changes Work Mode to 'Zero Export to CT'
Turns on Grid Charge for timing slot 6
Turns on 'Use Timer'

**Sunsynk: Force Discharge**
Changes Work Mode to 'Selling First'
Turns off Grid Charge for timing slot 6
Turns on 'Use Timer'

**Sunsynk: Stop Forced Charge/Discharge**
Changes Work Mode to 'Zero Export to CT'
Turns off Grid Charge for timing slot 6
Turns on 'Use Timer'

Within the Sunsynk app itself, I go to System Mode:

Set all timers to 00:00:00 (this means that by default, only the last timer (6) will be used, so we only need to update that from HA
