### ISSUE TITLE
iBoost Gas doesn’t switch on

### ISSUE THREAD

**Issue by PhillyGilly** [springfall2008/predbat_addon#47]
I have the settings below in my apps.yaml

```
  # iBoost settings for control of Immerion heaters
  switch.predbat_iboost_enable: True
  switch.predbat_iboost_energy_subtract: True
  iboost_energy_today:
    'sensor.immersion1_2_energy_today'
  # Disable boost functions and enable gas price comparison
  switch.predbat_iboost_solar: False
  switch.predbat_iboost_charging: False
  switch.predbat_iboost_gas: True
  input_number.predbat_iboost_gas_scale: 1.0
  # Gas rates for comparison
  metric_octopus_gas: 're:(sensor.(octopus_energy_|)gas_[0-9a-z]+_[0-9a-z]+_current_rate)'
  #iboost_energy_scaling: 1.0

```

Last night we had a few hours when the electricity price was lower than the gas price, but the binary sensor for iBoost active remained false.

I had had problems earlier in the day with an internet outage which caused BottleCap Dave's integration to stop working. At that time the Predbat log shows errors where the Octopus previous and current electricity rates couldn't be loaded but no mention of not loading the gas rates.
